##############################################################################
#    Copyright (C) 2021. All Rights Reserved

{
    'name': 'Skills',
    'version': '14.0.1',
    'author': "Ohia George - ohiageorge@gmail.com",
    'summary': 'INSETA MIS Skills Module',
    'depends': [
        'base', 
        'hr', 
        'mail',
        'base_automation', 
        'inseta_base', 
        'inseta_utils',
        'base_geolocalize',
        #'account_fiscal_year',
    ],
    'description': "INSETA MIS Skills Module",
    "data": [
            'security/inseta_skills_security.xml',
            'security/ir.model.access.csv',
            'reports/sdf_approval_letter.xml',
            'reports/sdf_rejection_letter.xml',
            'reports/wspatr_report_header.xml',
            'reports/wspatr_authorization_page.xml',
            'reports/atr_report.xml',
            'reports/wsp_report.xml',
            'reports/wspatr_report.xml',
            'reports/wspatr_approval_letter.xml',
            'reports/wspatr_rejection_letter.xml',
            'reports/organisation_approval_letter.xml',
            'reports/organisation_rejection_letter.xml',
            'data/mail_template.xml',
            'data/mail_data.xml',
            'data/automated_action.xml',
            'data/data.xml',
            'data/ir_config.xml',
            'sequence/sequence.xml',
            'security/ir_rule.xml',
            'views/res_users.xml',
            'wizard/inseta_wspatr_validate_views.xml',
            'wizard/inseta_sdf_register_rework_views.xml',
            'wizard/inseta_sdf_recommend_wizard_views.xml',
            'wizard/inseta_sdf_extend_reg_wizard_views.xml',
            'wizard/inseta_organisation_rework_wizard_views.xml',
            'wizard/inseta_skills_import_view.xml',
            'wizard/inseta_employer_update_wizard_views.xml',
            'views/inseta_sdf_views.xml',
            'wizard/inseta_wspatr_movetopivotal_wizard_views.xml',
            'wizard/inseta_wspatr_import_views.xml',
            'wizard/inseta_skills_report_wizard_views.xml',
            'wizard/inseta_assign_sdlno_wizard_views.xml',
            'wizard/inseta_wspatr_error_wizard_views.xml',
            'wizard/wizard_evaluation_approve_views.xml',
            'views/inseta_wspatr_views.xml',
            'views/inseta_wspatr_evaluation_views.xml',
            'views/inseta_wspatr_payment_views.xml',
            'views/inseta_organisation_view.xml',
            'views/base_views.xml',
            "views/res_financial_year_views.xml",
            'views/res_views.xml',
            'views/assets.xml',
        ],

    'css': [],
    'js': [],
    'qweb': [
        "static/src/xml/dhet_import_button.xml"
    ],
    "active": False,
    'application': True,
    "sequence": 3
}
